src/detail/reader/header.cpp
Was working with some data where one of VLR groups was empty, which caused a crash dereferencing the resultant empty vector. So, I added a guard for this case and everything appears to be functioning again.
Let me know if you need further tweaks to this PR.
Will
=> Fixed bug with dereferencing an empty vector

src/detail/writer/header.cpp
Encountered another dereference error on Windows, so this should take care of that.
=> * Fixed another dereference bug

csharp/dotnetLibLAS/dotnetLibLAS.csproj
Name of file was changed somewhere in a merge request, but project file was not updated. This resulted in a compile error.
=> Compile error

apps/laskernel.cpp
When attempting to transform a las file that is very definitely within the bounds of both UTM12 and both grid shift files, the following error occurs.
$ las2las --a_srs EPSG:26912+5713 --t_srs EPSG:26912+6647 test.las test2.las
pj_open_lib(HT2_0.gtx): call fopen(/usr/local/Cellar/proj/4.9.2/share/proj/HT2_0.gtx) - succeeded
GTX 2820x1290: LL=(-141.983333,41.0166667) UR=(-48.0166667,83.9833333)
pj_apply_vgridshift(): failed to find a grid shift table for
location (-115.4887439dW,0.0000000dN)
tried: HT2_0.gtx
ERROR 1: point not within available datum shift grids
error: Could not project point for ReprojectionTransform::point not within available datum shift grids0
This error seems to originate in laskernel.cpp at 1324, where it tries to reproject the bounds of the header. However, it …
=> Issue #76: las2las tries to reproject header bounds without setting coordinates.

apps/las2ogr.cpp, apps/ts2las.cpp
The lintian QA tool reported these spelling errors for the recent rebuild of the libLAS 1.8.0 Debian package with GDAL 1.11.4 and 2.0.2.
=> Fix 'parameters' & 'specified' typos.

include/liblas/spatialreference.hpp
libLAS 1.8.0 failed to build with libgeotiff 1.4.2RC2:
```make
[ 19%] Building CXX object src/CMakeFiles/las.dir/schema.cpp.o
cd /build/liblas-1.8.0/obj-x86_64-linux-gnu/src && /usr/bin/c++   -DHAVE_GDAL=1 -DHAVE_LIBGEOTIFF=1 -Dlas_EXPORTS -I/build/liblas-1.8.0/src/../include -I/usr/include/gdal -I/usr/include/geotiff -I/usr/include/x86_64-linux-gnu  -g -O2 -fdebug-prefix-map=/build/liblas-1.8.0=. -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -Wextra -Wall -Wno-unused-parameter -Wno-unused-variable -Wpointer-arith -Wcast-align -Wcast-qual -Wfloat-equal -Wredundant-decls -Wno-long-long -std=c++98 -ansi -fPIC   -o CMakeFiles/las.dir/schema.cpp.o -c /build/liblas-1.8.0/src/schema.cpp
In file included from …
```
=> Add support for libgeotiff 1.4.2.

apps/las2las.cpp
The spelling error was reported by the lintian QA tool for the Debian package build of 1.8.1RC1.
=> Fix 'offets' typo, replace with 'offset'.

apps/las2col.c, apps/las2pg.c
The endian support in las2col & las2pg needs a few extra defines to support GNU/kFreeBSD & GNU/Hurd along with GNU/Linux.
=> Add support for GNU/kFreeBSD & GNU/Hurd

apps/las2col.c, apps/las2pg.c
Additional spelling errors reported by the lintian QA tool, specifically in las2col & las2pg:
ouput     -> output
speficied -> specified
substract -> subtract
=> Fix spelling errors.

appveyor.yml, bin/appveyor/config.cmd, bin/appveyor/install.cmd
Configure Release build with OSGeo4W and AppVeyor's Boost 1.60.
------
Note, that due to [how AppVeyor handles organizations](https://www.appveyor.com/docs/team-setup/) (requires organizational account with dedicated e-mail), I decided it is easier to host AppVeyor builds on my account:
https://ci.appveyor.com/project/mloskot/liblas
=> Add basic AppVeyor configuration

apps/CMakeLists.txt
I noticed that I accidentally introduced some additional cmake code in my previous pull request that is doing nothing. This commit removes the unnecessary code, but keeps the fix introduced in that commit.
=> remove stale code doing nothing introduced by commit b1d14a846dda315ec7aa893b39917a6abd817cd0

apps/las2col.c, apps/las2las.cpp, apps/las2ogr.cpp, apps/laskernel.cpp, apps/ts2las.cpp, src/chipper.cpp, src/detail/reader/zipreader.cpp, src/gt_citation.cpp, src/header.cpp, src/spatialreference.cpp
- removes unused variables
- moves assignments around #ifdef to avoid unused vars
- checks return value and errors out when it should (ts2las.cpp)
- avoids redundant assignments
=> Code cleanups

apps/CMakeLists.txt, apps/memleak_test.c, src/c_api.cpp
Hi,
running applications that use the C API through valgrind, I realized that headers were not deallocated correctly. Going through the code I saw that the function LASHeader_Destroy was actually a no-op. 
This pull request adds a small test (a modified version of the bigfile_test), and changes the LASHeader_Destroy to deallocate the header. 
Please bear in mind that my C++ is very rusty, and this might very well not be the correct way to go about fixing the issue, however I have not encountered any problems so far.
Thanks,
Panos.
=> Memory leak in the C API

include/liblas/bounds.hpp
It is incorrect to return true immediately if it is true for only one dimension .
=> Fix bug in Bounds::contains(Bounds).

src/gt_citation.cpp
Recent clang/libc++ versions (from Xcode 9) reject invalid ordered pointer comparisons
=> fix pointer comparison

src/gt_citation.cpp
The call to GetAngularUnits(NULL) is ambiguous since there is now
```
double      GetAngularUnits( char ** ) const CPL_WARN_DEPRECATED("Use GetAngularUnits(const char**) instead");
double      GetAngularUnits( const char ** = nullptr ) const;
double      GetAngularUnits( std::nullptr_t ) const
```
But GetAngularUnits(NULL) doesn't match GetAngularUnits( std::nullptr_t )
This change is also compatible of previous GDAL version
=> gt_citation.cpp: fix compilation against GDAL 2.3

src/gt_citation.cpp, src/gt_citation.h, src/gt_wkt_srs.cpp, src/spatialreference.cpp
This applies on top of https://github.com/libLAS/libLAS/pull/133
=>  GDAL interface: no longer use deprecated API of GDAL 2.3 

src/spatialreference.cpp, src/transform.cpp
In DEBUG mode, OGRSpatialReference* and OGRSpatialReferenceH are not freely interchangeable in the C API
=> WITH_GDAL: fix build with -DDEBUG

CMakeLists.txt
CMake policy settings of `OLD` are not meant to be used as workarounds
for CMake's behavior changes. Instead, just set the property to `OFF` as
this is what setting the policy to `OLD` effectively does.
=> cmake: set CMAKE_MACOSX_RPATH to `OFF` explicitly

cmake/CMakeLists.txt
This is required because liblas-config.cmake refers to arch-specific
locations. Without this, 32bit liblas-config.cmake conflicts with 64bit
liblas-config.cmake on multi-arch distributions.
=> cmake: install liblas-config.cmake into lib/cmake

CMakeLists.txt
This fixes compiling problem when WITH_GEOTIFF is disabled, as GEOTIFF_LIBRARY is required by src/CMakeLists.txt, which has to be defined.
=> Fix compiling problem when WITH_GEOTIFF is disabled

include/liblas/detail/binary.hpp
BOOST_BIG_ENDIAN became deprecated in boost 1.69.0. But LIBLAS_BIG_ENDIAN can be used.
It solves the problem with deprecation and slightly reduces dependency on boost.
It solves: https://github.com/libLAS/libLAS/issues/165
=> Use LIBLAS_BIG_ENDIAN instead of BOOST_BIG_ENDIAN

apps/las2txt.cpp
I was trying to get the .las file header, but it was impossible.
With this change I finally figured it out.
Thanks!
=> Fix header missing from las2txt output

include/liblas/liblas.hpp
I was trying to use las2las to filter some points.
I always received : "Cannot open sample.las for read.  Exiting..."
The problem was that Open() didn't "return ifs" properly.
Thank you!
=> Always return NULL when Open() is used

src/c_api.cpp
std::istream* Open can return NULL as a result instead of throwing an exception. C API handles exceptions but does not check for NULL return value. Further manipulations with NULL pointer eventually lead to a segfault.
=> Fix segfault by handling a case when Open returns NULL

cmake/liblas-config.cmake.in
Boost 1.70 and newer use imported targets. This means that the same
Boost needs to be re-found when finding libLAS again.
=> liblas-config: find Boost when finding libLAS

CMakeLists.txt, src/CMakeLists.txt
Using rpath on macOS is tricky at best. Instead of forcing all macOS
users to deal with it, some package managers (e.g., MacPorts) avoid
@rpath completely. This logic forces settings on the deployment system
without a way to override it. These are best left controlled by the
`CMAKE_` variables which handle these properties by the user.
=> cmake: don't force rpath settings on macOS

apps/laskernel.cpp
Hi!
Some time ago I opened Issue libLAS#169 because I had a problem when I generated a cell without points.
Later I solved the problem, but I didn't comment on it. I recovered the solution after Diana's comment.
The problem is that RepairHeader() does not check for points before performing operations. I simply added a check to prevent from doing something if there are no points.
Thanks!
=> Avoiding segmentation fault when a cell is empty.

python/liblas/file.py
This PR addresses memory corruption in the python bindings caused by a double-free.
**The Problem**
When a `liblas.file.Header` is passed in to the `liblas.file.File` as a constructor parameter, its handle is copied to `self._header` and `self.ownheader` is set to `False`, but ` self.ownheader` is never read, and the rest of `class File` assumes it can call `LASHeader_Destroy(self._header)`.
When Python garbage collection runs, it calls `__del__` on the `Header` which results in its handle being destroyed. But, since creating the `File` already destroyed that handle (on one of the branches of `File.open`), this causes memory errors.
**This PR**
The simplest fix I could think of was to simply always copy the incoming handle and remove `self.ownheader` entirely.
**An alternative**
If you'd …
=> Avoid double-free when Header is passed into File.__init__

include/liblas/point.hpp
Make it clear that the GetX(),GetY(),GetZ() functions return the scaled and shifted coordinate values.
As a novice to libLAS it was not clear to me that these functions already applied the scaling and offset factors.
=> Clarification of Get{X,Y,Z} documentation

include/liblas/bounds.hpp
Small fix for a syntax error that occurs using gcc11 / c++20 mode. See [here](https://timsong-cpp.github.io/cppwp/n4861/diff.cpp17.class#2) for details:
=> Fix syntax error that occurs with gcc11

include/liblas/bounds.hpp, include/liblas/detail/endian.hpp
Fixes an out of bounds error when reading with a bounds filter with a 2D bounds.
=> Fix out of bounds error when filtering with 2D bounds

CMakeLists.txt
Currently I had the issue that a required Boost library was not requested, as `foreach` is a separate module (see https://github.com/microsoft/vcpkg/pull/30950). On the other side modules were requested, which are not required (`filesystem`).
So I checked which modules are really required im several steps:
1) Search for `#include.*boost/.*/` within current `master` branch, sort and deduplicate entries and check within with git submodule of Boost the required headers can be found (`<boost_root>\boost\\libs\<submodule>\include\<requested_header>`):
```
boost/algorithm/string/erase.hpp // algorithm
boost/any.hpp // any
boost/array.hpp // array
boost/bind.hpp // bind
boost/concept_check.hpp // concept_check
boost/config.hpp // config
boost/cstdint.hpp // config
boost/foreach.hpp // foreach …
```
=> Update required Boost modules list

cmake/liblas-config.cmake.in
Currently configuring VTK with libLAS fails with:
```
-- Reading /usr/lib64/cmake/libLAS/liblas-config.cmake
-- libLAS configuration, version 1.8.2b1
-- Found Boost: /usr/lib64/cmake/Boost-1.83.0/BoostConfig.cmake (found suitable exact version "1.83.0") found components: program_options thread system iostreams filesystem 
-- Found CGNS: /usr/include (found suitable version "4.40", minimum required is "4.10") 
-- Found Boost: /usr/lib64/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0") found components: serialization 
-- Found GDAL: /usr/lib64/libgdal.so (found version "3.8.4") 
-- Found Boost: /usr/lib64/cmake/Boost-1.83.0/BoostConfig.cmake (found version "1.83.0")  
-- Found OpenSlide: /usr/lib64/libopenslide.so  
-- Found LibArchive: /usr/lib64/libarchive.so (found version …
```
=> Synchronize Boost dependencies
